server:
  port: 5001
  mode: "dev"
bmt_user:
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: anhiuemlove33
  dbname: bmt_user
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
logger:
  log_level: debug
  file_log_name: "./storages/logs/dev.001.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true